version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      analyzers:
        patterns:
          - "Roslynator*"
          - "Meziantou*"
          - "*Analyzer*"
      testing:
        patterns:
          - "xunit*"
          - "NUnit*"
          - "CsCheck*"
          - "coverlet*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
